/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.compilers.demo

object App {
  def main(args: Array[String]): Unit = {
    println(greeting)
  }

  val greeting = "Hello, world!"
}
